In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 1. Handling Mising Data

In [17]:
df = pd.read_csv("students.csv")
df["StudentID"].dropna()
df["Age"].fillna(df["Age"].mean(), inplace = True)
df["GPA"].fillna(0, inplace = True)
df.fillna("NaN", inplace = True)

# 2. Encoding

## (1) Label Encoding

In [19]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_csv("students.csv")

df_label = df.copy()
le = LabelEncoder()

df_label["Gender Encoded"] = le.fit_transform(df["Gender"])

print("Label Encoded")
print(df_label[["Gender","Gender Encoded"]])

Label Encoded
     Gender  Gender Encoded
0      Male               1
1    Female               0
2    Female               0
3      Male               1
4      Male               1
..      ...             ...
195    Male               1
196    Male               1
197  Female               0
198  Female               0
199    Male               1

[200 rows x 2 columns]

## (2) One Hot Encoding

In [20]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df = pd.DataFrame({
    'City': ['New York', 'Paris', 'Tokyo', 'Paris'],
    'Age': [25, 30, 22, 35]
})

df_encoded = pd.get_dummies(df, columns=['City'])
print("OneHot Encoded")
print(df_encoded)

OneHot Encoded
   Age  City_New York  City_Paris  City_Tokyo
0   25           True       False       False
1   30          False        True       False
2   22          False       False        True
3   35          False        True       False

In [28]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.set_output(transform='pandas')

encoded_city = encoder.fit_transform(df[['City']])
print(pd.concat([df.drop(columns='City'), encoded_city], axis=1))

   Age  City_New York  City_Paris  City_Tokyo
0   25            1.0         0.0         0.0
1   30            0.0         1.0         0.0
2   22            0.0         0.0         1.0
3   35            0.0         1.0         0.0

# 3. Featrue Scaling

## Standard Scaling

In [10]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler = StandardScaler().set_output(transform="pandas")
x,y = load_wine(return_X_y=True, as_frame=True)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=42, shuffle=False)

scaled_x_train = scaler.fit_transform(x_train)

## Original Data

In [16]:
x.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0

## Scaled Data

In [15]:
scaled_x_train.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,1.407260,-0.264970,0.305640,-0.908535,1.722834,0.495300,0.768528,-0.437198,1.007482,0.849048,-0.185883,2.025675,0.735724
1,0.242870,-0.182089,-0.661011,-2.251159,-0.038940,0.223542,0.365919,-0.622858,-0.870432,0.074464,-0.124352,0.933206,0.692753
2,0.197651,0.504636,1.105628,0.006890,0.026311,0.495300,1.010093,-0.251539,1.974329,0.873638,-0.247413,0.449999,1.079489

## MinMaxScaling

In [17]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

scaler = MinMaxScaler().set_output(transform="pandas")
x,y = load_wine(return_X_y=True, as_frame=True)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=42, shuffle=False)

scaled_x_train = scaler.fit_transform(x_train)

## Original Data

In [18]:
x.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

## Scaled Data

In [19]:
scaled_x_train.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,0.842105,0.191700,0.572193,0.257732,0.619565,0.611511,0.552106,0.283019,0.593060,0.572178,0.336634,0.966805,0.561341
1,0.571053,0.205534,0.417112,0.030928,0.326087,0.557554,0.485588,0.245283,0.274448,0.406824,0.346535,0.751037,0.550642
2,0.560526,0.320158,0.700535,0.412371,0.336957,0.611511,0.592018,0.320755,0.757098,0.577428,0.326733,0.655602,0.646933
3,0.878947,0.239130,0.609626,0.319588,0.467391,0.989209,0.647450,0.207547,0.558360,0.855643,0.158416,0.771784,0.857347
4,0.581579,0.365613,0.807487,0.536082,0.521739,0.611511,0.470067,0.490566,0.444795,0.398950,0.336634,0.556017,0.325963

## Robust Scaling

In [6]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split

scaler = RobustScaler().set_output(transform="pandas")
x, y = load_wine(return_X_y=True, as_frame=True)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30,shuffle=False)

scaled_x = scaler.fit_transform(x_train)

## Original Data

In [5]:
x.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0

## Scaled Data

In [8]:
scaled_x.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,0.812392,-0.037915,0.299320,-0.654545,1.425,0.310680,0.491315,-0.153846,1.021459,0.677966,-0.086022,1.628319,0.549020
1,0.103270,0.094787,-0.489796,-1.721212,0.075,0.116505,0.193548,-0.307692,-0.712446,0.175474,-0.043011,0.707965,0.522876
2,0.075731,1.194313,0.952381,0.072727,0.125,0.310680,0.669975,0.000000,1.914163,0.693918,-0.129032,0.300885,0.758170